### ISSUE TITLE
Speed inversely propotional to import size

### ISSUE THREAD

**Issue by petercutting** [zdennis/ar-extensions#11]
ar_extensions is great. But does it bog down with large imports. Look at this data for various file sizes

file.................................num_recs........recs/sec
public/data/095LCQJ1.igc 3117 164
public/data/656C3X61.IGC 1224 348
public/data/657C3X61.IGC 809 420
public/data/65EC3X62.IGC 2150 234
public/data/65RC3X62.IGC 4140 117

I suspect there is a sweet spot for import size probably order 100 recs

Peter

PS does activerecord_import work on rails 2.3.9 ruby 1.8.7. I couldnt get it to work so used ar_extensions instead

**Comment by zdennis** [comment]
activerecord-import is not sanctioned to work on Rails 2.3.x (only Rails). If it does it is by coincidence and not intentional. ar-extensions is built for Rails 2.3.x.

Thank you for reporting the statistics. I'm closing this ticket out. If anything else feel free to re-open.

**Comment by petercutting** [comment]
Hi
I wasnt just reporting statistics. I was suggesting (poorly) that there could be a problem in the code somewhere as it grinds to a halt if you try to import too many records at a a time.
After some testing I now do an import every 100 recs (instead of every file =X000recs) and it more then doubled the import speed.
Switching off validations was also sweet too.
Peter
PS Is there a forum where I can ask how to get something working as I cannot get :on_duplicate_key_update to work. Or can I ask here

**Comment by zdennis** [comment]
@Peter, there is no forum, but I could set up a google mailing list if that would be helpful, otherwise you can feel free to ask here by opening a new issue for the specific question (this makes it easier for other folks to find if they have similar questions.

There are a number of things which can impact import speed, on both the server (db) and client (ruby) side. I am glad 100 records is a good sweet spot for you.
