### ISSUE TITLE
gem install of 0.9.2 (erroneously) installs activerecord 3.0.0 when activerecord 2.3.8 is already installed

### ISSUE THREAD

**Issue by blackrat** [zdennis/ar-extensions#9]
The list of dependencies for ar-extensions doesn't appear to be absolutely correct. I have a Ruby (non-rails) project that uses ar-extensions for bulk insertion of data into the mysql db, and requires activerecord and activesupport from the 2.3.8 rails branch. On a fresh machine, in order to install ar-extensions with these versions in place I have to do a 

gem install --ignore-dependencies ar-extensions

to prevent it from updating these (and adding in a number of other gems as a consequence).

Have I missed something, since I'm sure that I had ar-extensions working with 2.3.8 originally?

Paul

**Comment by zdennis** [comment]
I pushed ar-extensions 0.9.3 gems which has an updated gem dependency to be dependent on activerecord 2.1 up to but not including 3. No other functionality has changed. If you have activerecord 2.3.8 installed it will try to install 2.3.10 since that is the latest for the 2.3 series. The dependency is specified as activerecord "~> 2.1".

Let me know if any other questions. Thanks,
